### ISSUE TITLE
Need to download wordnet corpus (plus other first run feedback). 

### ISSUE THREAD

**Issue by carltongibson** [minho42/typofinder#1]
Hi @minho42. Super tool! 😄 

Should be part of the README I think: 

```
LookupError: 
**********************************************************************
  Resource wordnet not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('wordnet')
  
  For more information see: https://www.nltk.org/data.html```

**Comment by carltongibson** [comment]
Additional thoughts, maybe should be separate issues but: 

* It would be good if after "Find files", whilst it's extracting words, there some indication of progress, and that you can abort that. 
* In the final list, I wonder if it could pin back to the location in source. (I see that wouldn't be possible just yet, but it would be super cool) 

Anyhow +1! If you were to push this forward, I think it could be a really good tool. 🥇

**Comment by minho42** [comment]
Hi @carltongibson,
Thank you for trying and leaving feedback!

**Comment by minho42** [comment]
Opened a new issue
